// Generated by CoffeeScript 1.6.1
var getCookie, setCookie;

setCookie = function(name, value, expires, path, domain, secure) {
  var _ref, _ref1, _ref2, _ref3;
  return document.cookie = name + "=" + escape(value) + ((_ref = expires) != null ? _ref : "; expires=" + {
    expires: ""
  }) + ((_ref1 = path) != null ? _ref1 : "; path=" + {
    path: ""
  }) + ((_ref2 = domain) != null ? _ref2 : "; domain=" + {
    domain: ""
  }) + ((_ref3 = secure) != null ? _ref3 : {
    "; secure": ""
  });
};

getCookie = function(name) {
  var cookie, end, offset, search, setStr;
  cookie = " " + document.cookie;
  search = " " + name + "=";
  setStr = null;
  offset = 0;
  end = 0;
  if (cookie.length > 0) {
    offset = cookie.indexOf(search);
    if (offset !== -1) {
      offset += search.length;
      end = cookie.indexOf(";", offset);
      if (end === -1) {
        end = cookie.length;
      }
      setStr = unescape(cookie.substring(offset, end));
    }
  }
  return setStr;
};
